version: '3'
services:
    webserver:
        image: php:7.3.13-apache
        build:
            context: ./bin/webserver
        container_name: 'dev-server'
        restart: 'always'
        ports:
            - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
            - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
        volumes:
            - ${DOCUMENT_ROOT-./www}:/var/www/html
            - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
            - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
            - ${LOG_DIR-./logs/apache2}:/var/log/apache2
        links:
            - 'mysql'
    mysql:
        build:
            context: "./bin/mysql"
        container_name: 'dev-server-mysql'
        restart: 'always'
        ports:
            - "${HOST_MACHINE_MYSQL_PORT}:3306"
        volumes:
            - ${MYSQL_CONF_DIR-./config/mysql}:/etc/mysql/conf.d
            - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
            - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'dev-server-phpmyadmin'
        links:
          - 'mysql'
        environment:
          PMA_HOST: mysql
          PMA_PORT: "${HOST_MACHINE_MYSQL_PORT}:3306"
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - '8080:80'
        volumes:
          - /sessions
